"""
As of this release's B1/B2 protocol update, every clean-condition and
degradation-sweep file that table2_clean_merge.py and the rest of the
pipeline need is genuinely regenerated by an eval-only script from
existing checkpoints (see run_pipeline.sh) -- none of them are copied back
from their already-published location anymore.

The one exception is `D3_refined_grid_transformer_fd001_ensemble.json`,
which has no surviving generator script anywhere in this codebase
(discovered during the original export). It is read only, as a
"prior_D3_refined_crossover" comparison field, by
threshold_crossover_refinement.py, which does not itself produce it. It
ships as a frozen data file under results/degradation/; this script seeds
it back into results/generated/ for that one read.
"""
import os
import shutil

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJ_DIR = os.path.dirname(BASE_DIR)
DEGRADATION_DIR = os.path.join(PROJ_DIR, 'results', 'degradation')
GEN_DIR = os.path.join(PROJ_DIR, 'results', 'generated')
GEN_ATTR_DECISION_DIR = os.path.join(GEN_DIR, 'intermediate', 'attribution_and_decision')

os.makedirs(GEN_ATTR_DECISION_DIR, exist_ok=True)

MAPPING = {
    'threshold_refined_grid_transformer_fd001_ensemble.json': 'D3_refined_grid_transformer_fd001_ensemble.json',
}

if __name__ == '__main__':
    for src_name, dst_name in MAPPING.items():
        shutil.copy2(os.path.join(DEGRADATION_DIR, src_name), os.path.join(GEN_ATTR_DECISION_DIR, dst_name))
    print(f"Seeded {len(MAPPING)} frozen file(s) into results/generated/.")
